from django.urls import path

from . import views

urlpatterns = [
    path("employee/login", views.login_user, name="login_user"),
    path("employee/logout", views.logout_user, name="logout_user"),
    path("employee/changepassword", views.change_password, name="change_password"),
    path("dashboard", views.dashboard, name="dashboard"),
    path("dashboard/create", views.create, name="create"),
    path("dashboard/create/department/<int:id>", views.department_delete, name="department_delete"),
    path("dashboard/create/title/<int:id>", views.title_delete, name="title_delete"),
    path("dashboard/create/position/<int:id>", views.position_delete, name="position_delete"),
    path("dashboard/create/role/<int:id>", views.role_delete, name="role_delete"),
    path("employee/profile/personal", views.profile_personal, name="profile_personal"),
    path("employee/profile/work", views.profile_work, name="profile_work"),
    path("employee/profile/relationship", views.profile_relationship, name="profile_relationship"),
    path("employee/profile/relationship/update/<int:id>", views.profile_relationship_update, name="profile_relationship_update"),
    path("employee/profile/relationship/delete/<int:id>", views.profile_relationship_delete, name="profile_relationship_delete"),
    path("employee/profile/emergency/update/<int:id>", views.profile_emergency_update, name="profile_emergency_update"),
    path("employee/profile/emergency/delete/<int:id>", views.profile_emergency_delete, name="profile_emergency_delete"),
    path("employee/profile/education", views.profile_education, name="profile_education"),
    path("employee/profile/education/update/<int:id>", views.profile_education_update, name="profile_education_update"),
    path("employee/profile/education/delete/<int:id>", views.profile_education_delete, name="profile_education_delete"),
    path("employee/AddEmployee", views.addemp, name="addemp"),
    path("employee/MyTeam", views.team, name="team"),
    path("employee/MyTeam/delete/<int:id>", views.delete, name="delete"),
    path("employee/MyTeam/employee/<int:id>/personal", views.employee_personal, name="employee_personal"),
    path("employee/MyTeam/employee/<int:id>/work", views.employee_work, name="employee_work"),
    path("employee/MyTeam/employee/<int:id>/family", views.employee_family, name="employee_family"),
    path("employee/MyTeam/employee/family/relationship/update/<int:id>", views.employee_relation_update, name="employee_relation_update"),
    path("employee/MyTeam/employee/family/relationship/delete/<int:id>", views.employee_relation_delete, name="employee_relation_delete"),
    path("employee/MyTeam/employee/family/emergency/update/<int:id>", views.employee_emergency_update, name="employee_emergency_update"),
    path("employee/MyTeam/employee/family/emergency/delete/<int:id>", views.employee_emergency_delete, name="employee_emergency_delete"),
    path("employee/MyTeam/employee/<int:id>/education", views.employee_education, name="employee_education"),
    path("employee/MyTeam/employee/eduacation/update/<int:id>", views.employee_education_update, name="employee_education_update"),
    path("employee/MyTeam/employee/eduacation/delete/<int:id>", views.employee_education_delete, name="employee_education_delete"),
    path("employee/MyTeam/search", views.search, name="search"),
    path("employee/MyTeam/team_view/<int:id>", views.team_view, name="team_view"),
]