# Generated by Django 3.2.9 on 2022-01-20 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='priority',
            field=models.CharField(blank=True, max_length=125, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='end',
            field=models.DateField(help_text='MM/DD/YYYY', verbose_name='Course Start End'),
        ),
        migrations.AlterField(
            model_name='education',
            name='start',
            field=models.DateField(help_text='MM/DD/YYYY', verbose_name='Course Start Date'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='birthday',
            field=models.DateField(blank=True, help_text='MM/DD/YYYY', null=True, verbose_name='Date of Birth'),
        ),
    ]
